service: product-service1
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  products:
    handler: functions/get-products-list/get-products-list.getProductsList
    events:
      - http:
          method: get
          path: /products
          cors: true
  product:
    handler: functions/get-product-by-id/get-product-by-id.getProductById
    events:
      - http:
          method: get
          path: /products/{productId}
          cors: true
          request:
            parameters:
              paths:
                productId: true
