service: authorization-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  basicAuthorizer:
    handler: functions/basic-authorizer.basicAuthorizer
    environment:
      token: ${env:AUTH_TOKEN}
