service: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::shop-cloudfront-imported"
    - Effect: Allow
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::shop-cloudfront-imported/*"
    - Effect: Allow
      Action: "sqs:*"
      Resource:
        - "arn:aws:sqs:eu-central-1:602132075936:products-queue"

functions:
  importProducts:
    handler: functions/import-products/import-products-file.importProductsFile
    environment:
      bucket: ${env:BUCKET_NAME}
    events:
      - http:
          method: get
          path: /import
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            arn: "arn:aws:lambda:eu-central-1:602132075936:function:authorization-service-dev-basicAuthorizer"
            type: "request"
            name: basicAuthorizer
            resultTtlInSeconds: 0
  importFileParser:
    handler: functions/import-file-parser/import-file-parser.importFileParser
    environment:
      bucket: ${env:BUCKET_NAME}
      sqsName: ${env:QUEUE_NAME}
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
